services:
  utility-service:
    build: 
      context: .
      dockerfile: .
    
    env_file:
      - .env
    
    networks:
      - backend-networks
    
    ports:
      - "8000:8000"
    
    restart: unless-stopped